# install and import dependencies

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

## Details of the model are in https://tfhub.dev/google/movenet/multipose/lightning/1

# load model

In [1]:
import tensorflow as tf
import tensorflow_hub as hub
import cv2
from matplotlib import pyplot as plt
import numpy as np

In [2]:
#if using a GPU
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

In [3]:
gpus

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [10]:
model = hub.load('https://tfhub.dev/google/movenet/multipose/lightning/1')
movenet = model.signatures['serving_default']

# make detections

In [5]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    cv2.imshow('Movenet Multipose', frame)
    
    if cv2.waitKey(10)& 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [6]:
#plt.imshow(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
frame

array([[[ 81,  86,  95],
        [ 81,  86,  95],
        [ 82,  86,  97],
        ...,
        [ 87,  85,  95],
        [ 81,  81,  91],
        [ 76,  76,  86]],

       [[ 82,  87,  96],
        [ 82,  87,  97],
        [ 82,  86,  97],
        ...,
        [ 86,  84,  94],
        [ 82,  81,  91],
        [ 79,  79,  89]],

       [[ 82,  86,  97],
        [ 82,  86,  97],
        [ 83,  87,  99],
        ...,
        [ 84,  82,  92],
        [ 82,  81,  91],
        [ 82,  81,  91]],

       ...,

       [[162, 152, 129],
        [160, 151, 128],
        [159, 150, 127],
        ...,
        [115, 118, 100],
        [114, 117,  98],
        [113, 116,  97]],

       [[163, 150, 128],
        [163, 150, 128],
        [162, 151, 127],
        ...,
        [113, 117, 101],
        [114, 118, 100],
        [114, 118, 100]],

       [[165, 150, 128],
        [165, 151, 129],
        [165, 153, 129],
        ...,
        [113, 117, 102],
        [113, 117, 101],
        [115, 119, 102]]

In [5]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    #Resize image and detect
    img= frame.copy()
    img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0),256,256)#Multiples of 32
    input_img = tf.cast(img,dtype=tf.int32)
    
    # Detection section
    results = movenet(input_img)
    print(results)
    
    
    cv2.imshow('Movenet Multipose', frame)
    
    if cv2.waitKey(10)& 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[ 8.27122808e-01,  6.19367599e-01,  4.72600073e-01,
          7.39497304e-01,  6.98633075e-01,  6.05817497e-01,
          7.47948170e-01,  5.49058974e-01,  6.49594188e-01,
          7.80376434e-01,  7.83792973e-01,  4.65648204e-01,
          7.91766226e-01,  4.75111991e-01,  4.48389590e-01,
          8.99391830e-01,  8.14300299e-01,  1.57897566e-02,
          8.79507244e-01,  4.36473936e-01,  6.38379827e-02,
          8.91298532e-01,  8.47244084e-01,  2.84548500e-04,
          8.72239709e-01,  4.16977257e-01,  5.12307801e-04,
          8.62270713e-01,  7.60101378e-01,  1.92366131e-02,
          8.50585461e-01,  4.92311686e-01,  1.10220863e-02,
          7.69308925e-01,  7.95602024e-01,  1.54619375e-02,
          8.55345249e-01,  5.55143654e-01,  3.86660267e-03,
          7.71816611e-01,  7.70003855e-01,  2.13374104e-03,
          8.29771221e-01,  5.96589744e-01,  1.24442549e-02,
          5.39327979e-01,  6.852054

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[ 8.32529902e-01,  6.38661742e-01,  4.82546568e-01,
          7.45237708e-01,  7.03910828e-01,  5.34344733e-01,
          7.57105827e-01,  5.67053676e-01,  5.94971240e-01,
          7.86349118e-01,  7.88834333e-01,  5.52281201e-01,
          8.00613225e-01,  4.76902306e-01,  4.96898770e-01,
          8.94248664e-01,  8.27080965e-01,  7.11551076e-03,
          8.92853022e-01,  4.55668509e-01,  1.14354386e-03,
          8.72635841e-01,  8.36404979e-01,  1.11259484e-04,
          8.59850109e-01,  4.69034553e-01,  3.87944647e-06,
          8.59943271e-01,  7.60506988e-01,  3.75201739e-02,
          8.41166615e-01,  5.02924860e-01,  1.48186851e-02,
          8.64048481e-01,  7.95080960e-01,  5.33604389e-03,
          8.34320188e-01,  6.33087873e-01,  2.39279447e-03,
          8.68564367e-01,  7.61259615e-01,  4.84307413e-04,
          8.49547744e-01,  6.23946428e-01,  3.23483087e-02,
          7.39214599e-01,  7.732061

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[ 8.24473262e-01,  6.36056781e-01,  4.80848551e-01,
          7.47946978e-01,  7.02057123e-01,  5.04448473e-01,
          7.56113589e-01,  5.65433443e-01,  6.45750165e-01,
          7.91544795e-01,  7.88743019e-01,  5.65256715e-01,
          8.01618636e-01,  4.77106482e-01,  4.54766005e-01,
          8.93722236e-01,  8.07830691e-01,  1.71157753e-03,
          8.95668089e-01,  4.64933395e-01,  2.51229591e-04,
          8.69193077e-01,  8.12690735e-01,  1.53973106e-05,
          8.62774074e-01,  4.84852910e-01,  4.34621569e-07,
          8.58859539e-01,  7.46900320e-01,  2.79635862e-02,
          8.39514494e-01,  5.05266368e-01,  9.37711541e-03,
          8.60753059e-01,  7.88925469e-01,  7.31774187e-03,
          8.33821476e-01,  6.31161273e-01,  3.45663656e-03,
          8.65310073e-01,  7.58488476e-01,  8.83739442e-04,
          8.50427032e-01,  6.26176953e-01,  2.75112465e-02,
          7.39656031e-01,  7.738654

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[ 8.2303995e-01,  6.2842643e-01,  5.3612477e-01,  7.4352366e-01,
          6.9931257e-01,  5.5449325e-01,  7.5778717e-01,  5.5724460e-01,
          5.8883345e-01,  7.8836226e-01,  7.8538525e-01,  5.6084061e-01,
          8.0020142e-01,  4.7646633e-01,  4.6838713e-01,  8.9945000e-01,
          8.1945801e-01,  1.7340751e-02,  8.8970393e-01,  4.4769523e-01,
          2.3216052e-02,  8.9066780e-01,  8.5419804e-01,  2.8396203e-04,
          8.7328589e-01,  4.2920721e-01,  1.1325138e-04,  8.5798180e-01,
          7.5936925e-01,  3.1076331e-02,  8.4110153e-01,  5.0389284e-01,
          1.1737324e-02,  7.6628453e-01,  7.9858798e-01,  1.4911039e-02,
          8.4486812e-01,  5.6369746e-01,  5.3489013e-03,  7.7476108e-01,
          7.7381802e-01,  2.7124265e-03,  8.3771157e-01,  6.1973476e-01,
          3.2992084e-02,  5.3570348e-01,  7.0456886e-01,  5.1910966e-04,
          5.3738511e-01,  6.3962436e-01,  1.4263962e-03,  5

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[ 7.65121520e-01,  6.16433680e-01,  6.46002471e-01,
          7.00878024e-01,  6.74990952e-01,  5.49409986e-01,
          7.07679451e-01,  5.46973586e-01,  5.11083305e-01,
          7.57359028e-01,  7.59493351e-01,  3.77995551e-01,
          7.66878963e-01,  4.65946496e-01,  5.41808903e-01,
          9.12565708e-01,  8.34587693e-01,  6.55442523e-03,
          8.98326278e-01,  4.37127769e-01,  7.52172666e-03,
          9.01518941e-01,  8.41809452e-01,  9.06339556e-04,
          8.77940953e-01,  4.25112963e-01,  1.81301459e-06,
          8.65555167e-01,  7.29133487e-01,  3.15192118e-02,
          8.59250128e-01,  4.76038814e-01,  6.28515007e-03,
          8.86834502e-01,  7.57223725e-01,  1.51072221e-03,
          8.43643904e-01,  5.50618768e-01,  2.05458514e-02,
          8.37418199e-01,  8.31218004e-01,  1.88855221e-03,
          7.89454281e-01,  5.84131241e-01,  7.05027953e-02,
          5.37485361e-01,  6.967873

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[ 7.29842961e-01,  5.74935675e-01,  6.30627155e-01,
          6.68156207e-01,  6.35572791e-01,  4.53357935e-01,
          6.77914977e-01,  5.14996529e-01,  5.37452102e-01,
          7.38818705e-01,  7.17695892e-01,  4.01250213e-01,
          7.46568978e-01,  4.38736677e-01,  5.12942314e-01,
          8.99390459e-01,  7.65407026e-01,  5.57790836e-03,
          8.96134138e-01,  4.04630750e-01,  6.56193937e-04,
          8.86883318e-01,  7.59169579e-01,  3.05500544e-06,
          8.75451803e-01,  4.05421495e-01,  6.80660079e-08,
          8.63416970e-01,  7.04477012e-01,  3.59292552e-02,
          8.57710123e-01,  4.73007739e-01,  2.37758104e-02,
          8.82426798e-01,  7.21944809e-01,  1.76250091e-04,
          7.78612375e-01,  5.66505551e-01,  5.71584562e-03,
          8.77053559e-01,  7.31098235e-01,  9.52495262e-04,
          7.72256792e-01,  5.64271331e-01,  7.32092261e-02,
          5.72002172e-01,  6.834622

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[ 7.2289342e-01,  5.5539179e-01,  6.2969816e-01,  6.6691357e-01,
          6.1805785e-01,  6.5469772e-01,  6.7472404e-01,  4.9645725e-01,
          5.4765677e-01,  7.2700173e-01,  7.0296985e-01,  4.5028275e-01,
          7.5026506e-01,  4.3097210e-01,  5.1395303e-01,  9.0452898e-01,
          7.6842320e-01,  3.6397301e-02,  9.0411639e-01,  3.7263125e-01,
          4.4448217e-03,  8.9756298e-01,  7.7171654e-01,  1.5827578e-05,
          8.8800824e-01,  3.6837459e-01,  5.0553598e-07,  8.6549860e-01,
          6.7438054e-01,  2.4513837e-02,  8.6378437e-01,  4.5849210e-01,
          2.3449717e-02,  9.0187216e-01,  7.2296971e-01,  1.6221924e-04,
          7.6102597e-01,  5.4508042e-01,  1.4527092e-02,  8.7655896e-01,
          7.1597737e-01,  4.3313955e-03,  7.9073656e-01,  5.4602021e-01,
          4.7164373e-02,  5.5416638e-01,  6.4730072e-01,  4.6505911e-06,
          5.5174917e-01,  5.8674556e-01,  7.5926528e-07,  5

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[ 7.2336000e-01,  5.4588491e-01,  4.9453101e-01,  6.6765523e-01,
          6.0473901e-01,  4.3969560e-01,  6.7402697e-01,  4.8850480e-01,
          6.9032687e-01,  7.3241776e-01,  6.7995191e-01,  4.2436057e-01,
          7.4947399e-01,  4.1655877e-01,  5.0682342e-01,  8.8979173e-01,
          7.4485165e-01,  1.3103583e-03,  8.8654393e-01,  3.7085569e-01,
          1.3213335e-03,  8.7709767e-01,  7.4226314e-01,  3.8074018e-07,
          8.5876054e-01,  3.6688763e-01,  9.2462782e-05,  8.6083138e-01,
          6.6011381e-01,  2.2718869e-02,  8.3876222e-01,  3.8316107e-01,
          1.7595339e-03,  8.7859380e-01,  7.1500856e-01,  4.6485882e-05,
          7.8146833e-01,  5.3604317e-01,  1.0358894e-02,  8.6607927e-01,
          7.0169920e-01,  3.0579944e-03,  7.5783509e-01,  5.3061950e-01,
          6.4403445e-02,  6.2459433e-01,  6.5506995e-01,  4.1073045e-07,
          6.1627430e-01,  6.2863088e-01,  3.3581338e-07,  5

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[7.22629547e-01, 5.42366683e-01, 5.44046819e-01, 6.67298615e-01,
         6.02162659e-01, 4.53776866e-01, 6.75515592e-01, 4.83030647e-01,
         5.09688318e-01, 7.31957555e-01, 6.77225053e-01, 4.86691654e-01,
         7.55369306e-01, 4.17376548e-01, 4.86769706e-01, 9.00529146e-01,
         7.58316576e-01, 3.40241328e-04, 8.96390498e-01, 3.73643368e-01,
         1.94653927e-03, 8.88064444e-01, 7.57930100e-01, 1.00496954e-05,
         8.74614358e-01, 3.67999554e-01, 5.00373574e-07, 8.65255237e-01,
         6.61161542e-01, 4.58576828e-02, 8.56151819e-01, 3.79688621e-01,
         3.35126859e-03, 7.27437198e-01, 7.09428966e-01, 4.61277232e-04,
         7.61826515e-01, 5.40793478e-01, 3.37550975e-02, 8.73149276e-01,
         7.02507913e-01, 5.06167253e-03, 7.44345188e-01, 5.21608114e-01,
         5.17220274e-02, 5.88610411e-01, 6.55010581e-01, 3.31148378e-16,
         5.85280180e-01, 6.30218029e-01, 1.28801719e-14, 5.

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[7.25468695e-01, 5.45023978e-01, 5.36563098e-01, 6.70019567e-01,
         6.03444636e-01, 3.91909093e-01, 6.78746581e-01, 4.88316238e-01,
         6.45722628e-01, 7.32773483e-01, 6.79655015e-01, 5.17262220e-01,
         7.50685811e-01, 4.18188214e-01, 5.29202342e-01, 9.07220960e-01,
         7.70753205e-01, 4.12150612e-03, 9.02693212e-01, 3.57901067e-01,
         5.44942729e-03, 8.99116218e-01, 7.72646546e-01, 2.36247579e-05,
         8.88023913e-01, 3.51594716e-01, 6.23072253e-07, 8.68567050e-01,
         6.78921878e-01, 2.92630047e-02, 8.73193383e-01, 3.93957853e-01,
         2.68597202e-03, 9.04711425e-01, 7.27103949e-01, 2.11740626e-04,
         7.82628596e-01, 5.38703918e-01, 1.35860490e-02, 8.73700678e-01,
         7.03225553e-01, 6.75702514e-03, 7.59750366e-01, 5.31330705e-01,
         4.81453687e-02, 5.89770377e-01, 6.58018470e-01, 9.43397345e-15,
         5.85317850e-01, 6.16523981e-01, 1.12370826e-13, 5.

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[ 7.33362436e-01,  5.49118698e-01,  6.54679120e-01,
          6.76559627e-01,  6.06940567e-01,  5.02819836e-01,
          6.80319369e-01,  4.88074303e-01,  6.13433897e-01,
          7.33476937e-01,  6.78547204e-01,  5.53258896e-01,
          7.48489797e-01,  4.19564396e-01,  5.19552588e-01,
          9.05313551e-01,  7.65635967e-01,  9.33035091e-03,
          9.03077304e-01,  3.56615424e-01,  6.31656591e-03,
          9.02126610e-01,  7.68550277e-01,  7.07532454e-05,
          8.86929095e-01,  3.51658225e-01,  1.33445280e-06,
          8.66511285e-01,  6.61150873e-01,  3.45047116e-02,
          8.64372015e-01,  4.44240034e-01,  7.31701218e-03,
          7.45749652e-01,  7.09475040e-01,  2.76459643e-04,
          7.79127836e-01,  5.44535875e-01,  1.91093870e-02,
          8.92789483e-01,  7.61990607e-01,  3.54834180e-03,
          7.73245037e-01,  5.39649963e-01,  7.56133720e-02,
          5.59466183e-01,  6.717053

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[7.35696316e-01, 5.47094107e-01, 5.57422757e-01, 6.78373754e-01,
         6.06532097e-01, 5.67494512e-01, 6.85425460e-01, 4.87519115e-01,
         5.18116653e-01, 7.36614048e-01, 6.81735277e-01, 4.11073476e-01,
         7.49739289e-01, 4.17490900e-01, 5.58584154e-01, 9.06184077e-01,
         7.70237267e-01, 2.45150412e-03, 9.03635025e-01, 3.56019020e-01,
         3.91859328e-03, 9.00537014e-01, 7.71888435e-01, 1.57335253e-05,
         8.89102459e-01, 3.49838793e-01, 3.35726014e-07, 8.67128253e-01,
         6.61913216e-01, 3.34056541e-02, 8.63400400e-01, 4.56693381e-01,
         3.68605857e-03, 9.03256774e-01, 7.26282239e-01, 2.64720729e-04,
         7.99254298e-01, 5.35710037e-01, 1.15515394e-02, 8.73366058e-01,
         7.02431977e-01, 6.02504751e-03, 8.12310755e-01, 5.43016493e-01,
         5.71538657e-02, 5.88638127e-01, 6.57473326e-01, 2.12950276e-13,
         5.84103703e-01, 6.01529717e-01, 1.31134556e-12, 5.

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[7.37460554e-01, 5.50114274e-01, 5.82328737e-01, 6.79092050e-01,
         6.08961284e-01, 5.76875806e-01, 6.88065648e-01, 4.87264574e-01,
         6.29091442e-01, 7.34890699e-01, 6.80463552e-01, 4.44809496e-01,
         7.50683784e-01, 4.18602258e-01, 5.53333819e-01, 9.05148447e-01,
         7.59569466e-01, 3.35153774e-03, 9.05093610e-01, 3.70743632e-01,
         4.63610096e-03, 8.98420274e-01, 7.58486271e-01, 6.13334923e-05,
         8.90538454e-01, 3.69800240e-01, 8.61936996e-07, 8.66793454e-01,
         6.56837702e-01, 4.29902337e-02, 8.65591168e-01, 4.56447691e-01,
         5.51500870e-03, 7.32260942e-01, 7.23625898e-01, 1.92084946e-04,
         7.79716194e-01, 5.44902325e-01, 2.64465604e-02, 8.92445683e-01,
         7.64982045e-01, 3.97869572e-03, 8.11593831e-01, 5.44796944e-01,
         6.14087991e-02, 5.75159609e-01, 6.55759931e-01, 2.96989482e-11,
         5.71764827e-01, 5.86778104e-01, 3.71934428e-10, 5.

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[7.41356790e-01, 5.49623013e-01, 6.44430101e-01, 6.77924275e-01,
         6.08789325e-01, 5.80730200e-01, 6.88674212e-01, 4.84472305e-01,
         6.39527678e-01, 7.34292746e-01, 6.82539821e-01, 4.94381219e-01,
         7.53343523e-01, 4.19097424e-01, 5.39586663e-01, 9.06682074e-01,
         7.68828154e-01, 2.17503938e-03, 8.99112344e-01, 3.44193280e-01,
         8.31542443e-03, 8.98252785e-01, 7.71768034e-01, 2.84718208e-05,
         8.84092033e-01, 3.37979645e-01, 1.58838259e-06, 8.69594097e-01,
         6.74878597e-01, 3.81000377e-02, 8.65415156e-01, 4.42874938e-01,
         5.65993600e-03, 9.02947903e-01, 7.27833509e-01, 9.23090920e-05,
         7.79823661e-01, 5.45730710e-01, 1.92196332e-02, 8.91534388e-01,
         7.63375103e-01, 3.03503894e-03, 8.12396884e-01, 5.46984315e-01,
         5.04387431e-02, 5.60467124e-01, 6.71114385e-01, 1.93645395e-11,
         5.56866169e-01, 5.87951958e-01, 5.22582477e-10, 5.

{'output_0': <tf.Tensor: shape=(1, 6, 56), dtype=float32, numpy=
array([[[ 7.51084924e-01,  5.48946857e-01,  6.25406682e-01,
          6.81428373e-01,  6.09212160e-01,  4.83535618e-01,
          6.93564296e-01,  4.86871034e-01,  6.23632014e-01,
          7.32770026e-01,  6.87069297e-01,  3.60736668e-01,
          7.55780995e-01,  4.20161456e-01,  5.28266311e-01,
          9.04519558e-01,  7.66564965e-01,  2.32254788e-02,
          8.96414340e-01,  3.59411210e-01,  5.94755728e-03,
          8.98965895e-01,  7.70186186e-01,  2.58198179e-05,
          8.84250104e-01,  3.52968454e-01,  2.88163545e-04,
          8.70494246e-01,  6.85400963e-01,  3.44364531e-02,
          8.58422637e-01,  4.57274199e-01,  2.92213410e-02,
          9.00666595e-01,  7.27425635e-01,  1.58660827e-04,
          8.62046599e-01,  5.24760127e-01,  1.10551175e-02,
          8.88602138e-01,  7.33559191e-01,  3.38659598e-03,
          8.25467169e-01,  5.44588447e-01,  3.40494402e-02,
          5.87574840e-01,  6.587931

In [ ]:
cap.release()
cv2.destroyAllWindows()

- x,y,score * 17 =51 + 5(edge)

In [ ]:
results['output_0'].numpy()[:,:,:51].shape

In [ ]:
results['output_0'].numpy()[:,:,:51]

In [ ]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    #Resize image and detect
    img= frame.copy()
    img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0),256,256)#Multiples of 32
    input_img = tf.cast(img,dtype=tf.int32)
    
    # Detection section
    results = movenet(input_img)
    keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
    print(keypoints_with_scores)
    
    
    cv2.imshow('Movenet Multipose', frame)
    
    if cv2.waitKey(10)& 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [ ]:
keypoints_with_scores[0].shape

In [5]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 6, (0,255,0), -1)

# draw edges

In [6]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

In [7]:
def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 4)

In [8]:
# Function to loop through each person detected and render
def loop_through_people(frame, keypoints_with_scores, edges, confidence_threshold):
    for person in keypoints_with_scores:
        draw_connections(frame, person, edges, confidence_threshold)
        draw_keypoints(frame, person, confidence_threshold)

In [10]:
frame.shape

(480, 640, 3)

In [11]:
480/640

0.75

In [12]:
256*0.75

192.0

In [ ]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    #Resize image and detect
    img= frame.copy()
    img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0),192,256)#Multiples of 32
    input_img = tf.cast(img,dtype=tf.int32)
    
    # Detection section
    results = movenet(input_img)
    keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
    
    # Render keypoints 
    loop_through_people(frame, keypoints_with_scores, EDGES, 0.3)
    
    
    cv2.imshow('Movenet Multipose', frame)
    
    if cv2.waitKey(10)& 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [12]:
cap = cv2.VideoCapture('novak.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    
    # Resize image
    img = frame.copy()
    img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0), 384,640)
    input_img = tf.cast(img, dtype=tf.int32)
    
    # Detection section
    results = movenet(input_img)
    keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
    
    # Render keypoints 
    loop_through_people(frame, keypoints_with_scores, EDGES, 0.1)
    
    cv2.imshow('Movenet Multipose', frame)
    
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [6]:
pip list

Package                            Version
---------------------------------- -------------------
-ensorflow-gpu                     2.7.0
absl-py                            0.14.1
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 2.0.3
anaconda-project                   0.9.1
anyio                              2.2.0
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.5
astropy                            4.2.1
astunparse                         1.6.3
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.6
Babel                              2.9.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.